### ISSUE TITLE
Add support for private git repo

### ISSUE THREAD

**Issue by lacombar** [rodrigo-brito/gocity#11]

**Comment by lacombar** [comment]
if anybody is interested, it can be hacked quickly with:

```
diff --git a/lib/fetch.go b/lib/fetch.go
index 8f875be..ba63b02 100644
--- a/lib/fetch.go
+++ b/lib/fetch.go
@@ -27,7 +27,9 @@ func (fetcher) packageFound(name string) bool {
 }

 func (f *fetcher) Fetch(name string) error {
-       gitAddress := fmt.Sprintf("https://%s", name)
+       gitAddress := "https://"
+       gitAddress += "<your-api-key>"
+       gitAddress += name
        folder := fmt.Sprintf("%s/src/%s", os.Getenv("GOPATH"), name)

        _, err := git.PlainClone(folder, false, &git.CloneOptions{
```

**Comment by lacombar** [comment]
it would be great if the backend could directly these credentials from `~/.gitconfig` following `https://git-scm.com/docs/gitcredentials`

**Comment by rodrigo-brito** [comment]
Hi @JackTiger, I'm planing to include a binary version to extract data and run the server locally or in an server. Maybe in the next month.

**Comment by JackTiger** [comment]
@rodrigo-brito How's it going, really looking forward to this feature!

**Comment by lacombar** [comment]
@JackTiger I hack away a version shortly after opening this issue, available in my fork in the `wip` branch. Private repo support only require you to edit `lib/fetch.go` on line 31 to add your api key.

**Comment by rodrigo-brito** [comment]
Hi @JackTiger, I saw your job with the MemoryStorage, very nice. Feel welcome to contribute with the project. It will be a nice contribution.

About the support to private repositories, I pretend to transform the project in a CLI command. The CLI receive a project URL ou local path and run the GoCity locally, I think it can reduce security issues and solve this problem.

**Comment by rodrigo-brito** [comment]
Hi @JackTiger and @lacombar 
Now you can install gocity locally and open private projects in $GOPATH with:
```
gocity open github.com/youruser/projectname
```
It will open a server in localhost.

**Comment by JackTiger** [comment]
Very Nice, I Can't wait to try it. Thank you very much!

**Comment by JackTiger** [comment]
@rodrigo-brito Hi, When I use this cmd to open a local project, display the message as below:

```
D:\progma\Go\bin>gocity.exe open github.com/adohe/etcd-dashboard
2019/02/18 13:53:18 dialing: google: could not find default credentials. See htt
ps://developers.google.com/accounts/docs/application-default-credentials for mor
e information.
```

If I ignore some of the steps when open a local project?

**Comment by rodrigo-brito** [comment]
Hi @JackTiger, the application uses static files from https://go-city.github.io. Were you connected in the internet during the tests?

**Comment by JackTiger** [comment]
I have connected to the internet. Can I download the application uses static files manual? 
By the way, Can I direct analysis local directory path using gocity?

@rodrigo-brito

**Comment by rodrigo-brito** [comment]
It is possible to analysis if your repository is stored inside GOPATH. The static files (Front-end) are not present in application, but it can be improved easily.

**Comment by rodrigo-brito** [comment]
The application works fine in Linux/Mac. Are you using windows, right? I will try to test it on a virtual machine later and report to you!

**Comment by JackTiger** [comment]
@rodrigo-brito  Yes I test in windows system. But I test in linux in the early, but I got the error:

```
http: proxy error: x509: certificate signed by unknown authority.
/usr/bin/xdg-open: line 461: links2: command not found
/usr/bin/xdg-open: line 461: links: command not found
/usr/bin/xdg-open: line 461: lynx: command not found
```

```
my linux system env is as below:
3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

so I think the application uses static files can be intergeted in gocity repository, that is the best way to use this function local.

**Comment by rodrigo-brito** [comment]
It is failing to open your browse (The command open the browser automatically). If you access the URL directly, it works? http://localhost:4000/#/github.com/adohe/etcd-dashboard

**Comment by rodrigo-brito** [comment]
I agree, the integration of static files can help a lot this process.

**Comment by JackTiger** [comment]
Yes, I access the URL directly, but it does not work, so I do not know what can I do.

**Comment by JackTiger** [comment]
I suggest release a version that has the integration of static files, so the user can install and use directly.

**Comment by JackTiger** [comment]
By the way, I think gocity can calculate scores of the golang project, the result can be one of the indicators to evaluate code quality. That is very great! @rodrigo-brito

**Comment by JackTiger** [comment]
I hava a question. Now gocity only support show the path beginning with github.com url? not the local gopath directory.

I just test home. I found I can connect to the internet. But I find I can only show the project beginning with github.com in my gopath. At the same time, when I open gocity local, If I want to redirect the file in  the gocity web, I fount it directly link to github website not my local gopath code. @rodrigo-brito

**Comment by rodrigo-brito** [comment]
Yes, the code location is based on `github.com/...` URL. The code retrieving for local files is a good feature. But, the browser may not work as expected, maybe it will be possible only with a external editor.

**Comment by rodrigo-brito** [comment]
Hi @JackTiger, now the static files are completly embedded on binary. Make a new try and give a feedback.

**Comment by rodrigo-brito** [comment]
I'm closing it for now. But it is working for private repositories. If a new issues appear, please comment bellow to reopen it.
