### ISSUE TITLE
All my repos return an "Error during plot" error

### ISSUE THREAD

**Issue by onodera-punpun** [rodrigo-brito/gocity#12]
Is this something on my side or..? Examples:

https://github.com/onodera-punpun/prt
https://github.com/onodera-punpun/sako
https://github.com/onodera-punpun/prt
https://github.com/onodera-punpun/melonbar

**Comment by rodrigo-brito** [comment]
The server disk is full. I'm working on it right now.
Thanks for the report.

**Comment by rodrigo-brito** [comment]
@onodera-punpun Now it is working: https://go-city.github.io/#/github.com/onodera-punpun/prt

**Comment by onodera-punpun** [comment]
Thanks 👍
