### ISSUE TITLE
Model has incorrect color for less than 2000 lines code

### ISSUE THREAD

**Issue by aquelehugo** [rodrigo-brito/gocity#14]
Your example on Cobra ( https://go-city.github.io/#/github.com/spf13/cobra ) shows a model rendered in black. According to the legend, black models represent 2000+ lines files, but the represented file is only 1571 lines long.

![image](https://user-images.githubusercontent.com/8480411/48288415-2a6cec00-e453-11e8-9571-9b80562facf4.png)

![image](https://user-images.githubusercontent.com/8480411/48289833-f0521900-e457-11e8-8712-cf6faeb09371.png)

**Comment by rodrigo-brito** [comment]
Hi @aquelehugo, thank you for the report. It is very close to black . [GQLGen](https://go-city.github.io/#/github.com/99designs/gqlgen) is a good example of the black level. 
![black](https://user-images.githubusercontent.com/7620947/48290569-7bcca980-e45a-11e8-8fe6-14cacb856ad8.png)

**Comment by aquelehugo** [comment]
But is gray-like black, it should be blueish u.u

**Comment by rodrigo-brito** [comment]
The file color ranges between light gray and black, the blue color is used only for structs.

**Comment by aquelehugo** [comment]
You're right. I didn't relate the type color system with the line count color system. PICNIC kind of issue here :rofl:
