### ISSUE TITLE
How to reset the cache?

### ISSUE THREAD

**Issue by rohmanhm** [rodrigo-brito/gocity#15]
I had plot my repo on **GoCity** before.

Now that I have changed my code, the files and folder structure are completely different, but **GoCity** shows the same visual as before.

Here's https://go-city.github.io/#/github.com/rohmanhm/go-open-dir
try to `Open on Github` file `main.go` it will shows **Page Not Found**

**Comment by rodrigo-brito** [comment]
Hi @rohmanhm , actualy we have two levels of cache. The cache memory resets in 48 hours and the Google Storage Cache resets with 72 hours. I set it so loong to avoid issues with processing in the first week, but I will reduce it soon.

I can provide a button to reset the cache, but I'm a little afraid about attacks. It can get the server down in minutes.

**Comment by rohmanhm** [comment]
Adding the reset button I think it's fine, and to prevent the attacks maybe you can add reset tries limit.

BTW, It's been 4 days (96 hours) and the result of my repo still the same.

**Comment by rodrigo-brito** [comment]
Hi @rohmanhm, I agree. It can be a small issue with the cache TTL, I restart the cache manually and works fine now. Thank you for the report. I will investigate it soon.

**Comment by rodrigo-brito** [comment]
Hi @rohmanhm, I disabled the GCP cache. It is not a problem, any more.
