### ISSUE TITLE
Add badge generator

### ISSUE THREAD

**Issue by CorentinB** [rodrigo-brito/gocity#16]
Hi!
It would be sweet to have beside the star and fork button at the top right corner, a badge generator, that simply link to the repo, like any other badge system it would simple generate a little markdown snippet for those who want to include a link to their code through gocity it in their README.

I think it's a fun idea, I'd like to do the PR myself but I'm really bad at designing anything graphical, so if someone is up for designing a little badge for gocity?

Have a nice day!

**Comment by rodrigo-brito** [comment]
Hi @CorentinB,
Very interesting idea!

**Comment by CorentinB** [comment]
I'm gonna try to work on a badge this week end, it's time to get some graphics skills!
I'll get back to you.

**Comment by rodrigo-brito** [comment]
Thank you. It will be a great contribution. :trophy:

**Comment by CorentinB** [comment]
Sorry I didn't get back to you, I didn't have the time to do a badge.
But I saw this: https://shields.io/
Maybe it could be a starting point. It allows the generation of custom badges if I understood correctly.

**Comment by ellisonleao** [comment]
is this still a task? i can give it a try if its available.

**Comment by rodrigo-brito** [comment]
Hi @ellisonleao. It's available.
