### ISSUE TITLE
Receive branch name as parameter

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/gocity#17]
We used `master` as default branch. Threfore, other branches can be uses. Maybe, it can be informed by a query param when requested.

Ref https://github.com/rodrigo-brito/gocity/blob/master/model/node.go#L167

**Comment by Avni-Sharma** [comment]
Hi, I would like to work on this

**Comment by rodrigo-brito** [comment]
Have fun @Avni-Sharma

**Comment by rodrigo-brito** [comment]
Hi @Avni-Sharma, how its going on?

**Comment by Avni-Sharma** [comment]
Yeah sure. That might help :)

**Comment by rodrigo-brito** [comment]
You should include one parameter in function New (https://github.com/rodrigo-brito/gocity/blob/master/model/node.go#L110) for the branch. And receive it as query parameter, as the same as project URL (https://github.com/rodrigo-brito/gocity/blob/6ae7b2d5b777dedadaeacf8b0f6b0521cb1c2ae4/handle/analyzer.go#L27).

To start the project locally, just run `go run main.go server`
