### ISSUE TITLE
Improve Coverage

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/gocity#23]
This issue is valid until we reach 100% of coverage :smile:. The current coverage is [![codecov](https://codecov.io/gh/rodrigo-brito/gocity/branch/master/graph/badge.svg)](https://codecov.io/gh/rodrigo-brito/gocity).
You can help with a simple test case. :+1:

**Comment by edenriquez** [comment]
Hi @rodrigo-brito ✋ 
I would like to cover 
`github.com/rodrigo-brito/gocity/analyzer` 
if it is ok for you.

**Comment by rodrigo-brito** [comment]
Hi @edenriquez, it's ok. Thank you for the support.
