### ISSUE TITLE
Include Go Linters in Github Actions

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/gocity#24]
The GitHub actions are running tests but linter are not included.
There are a lot of example of code here: https://github.com/cedrickring/golang-action
Choose some linter and have fun.

**Comment by pavan-kalyan** [comment]
I would like to work on this, if that's okay ?

**Comment by rodrigo-brito** [comment]
Hi @pavan-kalyan. It's ok.

**Comment by rodrigo-brito** [comment]
Thank you @pavan-kalyan.
Closed by https://github.com/rodrigo-brito/gocity/pull/30
