### ISSUE TITLE
Localhost Redirect

### ISSUE THREAD

**Issue by RafaelGomides** [rodrigo-brito/gocity#25]
### Description
When I start the server using: `go run main.go server`. The system starts normally and displays the URL: `http://localhost:4000`. The problem is that when accessing the URL the server loops trying to redirect the client to `http://localhost:4000//`. This even prevents the use of the `open` command, which when entering the display URL presents the same problem.

### Steps to Problem

1. Clone Repo;
2. Use `make` to install dep;
3. Run using `go run main.go server`;
4. Use the URL provided;
5. See server logs in terminal;

[![asciicast](https://asciinema.org/a/271888.svg)](https://asciinema.org/a/271888)

**Comment by rodrigo-brito** [comment]
Hi @RafaelGomides, thank you for the report. I think it is related to static files redirect, I will investigate and report details later.

**Comment by rodrigo-brito** [comment]
Hi @RafaelGomides, can you try again? It seems a bug in packr and fixed by @bombsimon

**Comment by RafaelGomides** [comment]
This problem is solved, but the client url still wrong.

![Screenshot from 2019-10-01 17-54-28](https://user-images.githubusercontent.com/5471480/66000041-048a7480-e475-11e9-8277-9d220a9365aa.png)

`localhost:4000//`

**Comment by rodrigo-brito** [comment]
It's normal here, maybe a cache in your browser.
