### ISSUE TITLE
Create a test file for cors.go

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/gocity#44]
A simple file that creates a cors middleware
https://github.com/rodrigo-brito/gocity/blob/master/handle/middlewares/cors.go

**Comment by ShajithaMohammed** [comment]
@rodrigo-brito  I would like to work on this.

**Comment by rodrigo-brito** [comment]
Closed by https://github.com/rodrigo-brito/gocity/pull/63
