### ISSUE TITLE
Create a test file for headers.go

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/gocity#45]
A simple file that handles HTTP headers
https://github.com/rodrigo-brito/gocity/blob/master/handle/middlewares/headers.go

**Comment by Ashwithabg** [comment]
@rodrigo-brito Can I work on this issue?

**Comment by rodrigo-brito** [comment]
Hi @Ashwithabg.
Yes! Have fun!

**Comment by Ashwithabg** [comment]
@rodrigo-brito Currently for my PR coverage is failing
![image](https://user-images.githubusercontent.com/20147948/95872403-62da7a80-0d8c-11eb-9ba9-22c4f7840f78.png)

headers spec is having 100% coverage
