### ISSUE TITLE
Replace Packer by Pkger

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/gocity#46]
Currently, we are using `gobuffalo/packr` to embed static files.
Pkger is the successor of packer for static files
More info: https://github.com/markbates/pkger

**Comment by faabiosr** [comment]
Hi Mate! I'll try to do this issue.

**Comment by rodrigo-brito** [comment]
Hi @faabiosr, have fun!

**Comment by rodrigo-brito** [comment]
I started this issue in the morning, the working in progress is in [pkger](https://github.com/rodrigo-brito/gocity/tree/pkger) branch. Maybe it can help you.
