### ISSUE TITLE
Eliminate utils package

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/gocity#47]
This issue consists in move all methods from the utils package to another package.
Suggestion `utils` -> `lib/file`.

**Comment by rodrigo-brito** [comment]
Hi @HemantJoshi11. The refactoring consists in move the code to an appropriated package. The main idea of the issue is to avoid `utils` package.

**Comment by HemantJoshi11** [comment]
Ok. Is using utils package anti pattern ?

**Comment by rodrigo-brito** [comment]
Yes!
A good article is found here: https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

**Comment by HemantJoshi11** [comment]
Ok . I will do needed refactoring
