### ISSUE TITLE
Include Codecov in github actions

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/gocity#51]
Include Codecov actions in project workflow
More details here: https://github.com/codecov/codecov-action

**Comment by rodrigo-brito** [comment]
A real example here: https://github.com/codecov/example-go

**Comment by tullur** [comment]
Hi, @rodrigo-brito!
I'll try to do this issue.

**Comment by rodrigo-brito** [comment]
Hi @tullur, have fun!
