### ISSUE TITLE
How can I get my own google credentials

### ISSUE THREAD

**Issue by goodweather0** [rodrigo-brito/gocity#6]
I ran this project , and my ide told me "dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."

Is this project might use google public server ?

thanks 
---env---
go version : 1.8
platform : windows7
IDE : vscode

**Comment by rodrigo-brito** [comment]
I used the Google cloud storage to save the output of processing. To run, you need to create a bucket on Google Cloud and place the credentials file in the project root. I will try to make it idependent. I agree, it is a unnecessary dependency.
